### ISSUE TITLE
When I try to run inference.py, CUDA out of memory

### ISSUE THREAD

**Issue by ievenight** [yxlu-0102/MP-SENet#53]
Try running `python inference.py --checkpoint_file best_ckpt/g_best_vb --output_dir generated_files/MP-SENet_VB`

Error message: RuntimeError: CUDA out of memory. Tried to allocate 65.98 GiB (GPU 0; 79.32 GiB total capacity; 66.97 GiB already allocated; 9.65 GiB free; 67.96 GiB reserved in total by PyTorch)

I tried modifying the batch size and other parameters, but I still get OOM. Could you please suggest a suitable method for me to use the best_ckpt for inference normally?

I am using an A100-80G GPU, but it still runs out of memory (OOM). Is there a way to run inference on a GPU with less than 24G without OOM?

Thanks

**Comment by JacobLinCool** [comment]
I tested the memory requirements on a 48G A40. You can see the results here: https://github.com/JacobLinCool/MPSENet#memory-usage-and-speed

![usage](https://github.com/user-attachments/assets/6b97d1bd-9229-4537-a88f-17c86c7fb434)

Since the model is trained on 2-second segments, my package defaults to splitting the input audio into 2-second segments, which requires only 1G of RAM to run inference. However, if your audio is very noisy and the main speaker's volume is close to the other speakers, you may want to use a larger `segment_size` for better consistency. (If you have a 24G GPU you can safely set it to `16000 * 10` or even `16000 * 15`)

**Comment by ievenight** [comment]
Thank you very much, it's successfully resolved!
