### ISSUE TITLE
a question about inference

### ISSUE THREAD

**Issue by lth456321** [yxlu-0102/MP-SENet#9]
Thank you very much for your paper and the disclosure of the code. I have a question about the inference. I used the provided ckpt and used inference. py to generate enhanced speech, and then used cal_metrics. py file calculates metrics, but the metrics differ significantly from those in the article. Throughout the process, I only replaced librosa.load with soundfile.read, as librosa.load does not work on my computer. Can you help me analyze the reasons for this result? Anyway, thank you again.

**Comment by yxlu-0102** [comment]
Thanks for your interest in our work, I re-downloaded the MP-SENet code in this repo and generated speech with `librosa` and `soundfile` respectively. After calculating results by  `cal_metrics.py`, the objective results of both read methods are the same, namely 
- pesq: 3.495735651659734 
- csig: 4.727512378614241 
- cbak: 3.950338723236475 
- covl: 4.224942893521928
- ssnr: 10.640891073683255
- stoi: 0.9602032202555391. 

These results are consistent with our Interspeech paper. So, this issue is not related to the`soundfile`. Perhaps you can check if your dataset is consistent with ours.
